In [1]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
file = files.upload()

Saving cars93.csv to cars93.csv

In [ ]:
df = pd.read_csv("cars93.csv")

In [ ]:
df.head(5)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0

In [ ]:
print("Rows: ", df.shape[0])
print("Columns: ", df.shape[1])

Rows:  93
Columns:  10

In [ ]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Price', 'MPG.city', 'AirBags',
       'Horsepower', 'Passengers', 'Rear.seat.room', 'Luggage.room'],
      dtype='object')

In [ ]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,9.300000e+01,93.000000,93.000000,93.000000,91.000000,82.000000
mean,3.999484e+06,22.365591,143.827957,5.086022,27.829670,13.890244
std,1.980183e+06,5.619812,52.374410,1.038979,2.989072,2.997967
min,1.517000e+06,15.000000,55.000000,2.000000,19.000000,6.000000
25%,2.501000e+06,18.000000,103.000000,4.000000,26.000000,12.000000
50%,3.628500e+06,21.000000,140.000000,5.000000,27.500000,14.000000
75%,4.776500e+06,25.000000,170.000000,6.000000,30.000000,15.000000
max,1.268950e+07,46.000000,300.000000,8.000000,36.000000,22.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     int64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(2), int64(4), object(4)
memory usage: 7.4+ KB

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
df['Rear.seat.room'].mean()

np.float64(27.82967032967033)

In [ ]:
x = df['Rear.seat.room'].median()

In [ ]:
df['Rear.seat.room'] = df['Rear.seat.room'].fillna(value = x)

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room      11
dtype: int64

In [ ]:
df['Luggage.room'].mean()

np.float64(13.890243902439025)

In [ ]:
df['Luggage.room'].median()

14.0

In [ ]:
x = df['Luggage.room'].median()

In [ ]:
df['Luggage.room'] = df['Luggage.room'].fillna(value = x)

In [ ]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [ ]:
df['AirBags'].mode()

0    Driver only
Name: AirBags, dtype: object

In [ ]:
x = df['AirBags'].mode()[0]

In [ ]:
df['AirBags'] = df['AirBags'].fillna(value = x)

In [ ]:
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,7728500,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,6150000,22,Driver only,208,4,27.0,13.0

Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
min_max = MinMaxScaler()

In [ ]:
price_normalized = min_max.fit_transform(df[['Price']])

In [ ]:
price_normalized.min()

np.float64(0.0)

In [ ]:
price_normalized.max()

np.float64(1.0)

Add the new normaalized column into existing dataframe

In [ ]:
df['price_normalized'] = price_normalized

In [ ]:
df.head(3)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room,price_normalized
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0,0.155963
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0,0.486239
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0,0.398165

Performing Standardization on Horse Power

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
std_scaler =  StandardScaler()

In [ ]:
hoursepower_std = std_scaler.fit_transform(df[['Horsepower']])

In [ ]:
hoursepower_std.min()

np.float64(-1.705210877485415)

In [ ]:
hoursepower_std.max()

np.float64(2.998000579179055)

In [ ]:
df['Horsepower_std'] = hoursepower_std

In [ ]:
df.head(3)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room,price_normalized,Horsepower_std
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0,0.155963,-0.073484
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0,0.486239,1.078322
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0,0.398165,0.540813

Data Encoding: One Hot Encoding

In [ ]:
df_encoded = pd.get_dummies(df)

In [ ]:
df_encoded.shape

(93, 141)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Manufacturer      93 non-null     object
 1   Model             93 non-null     object
 2   Type              93 non-null     object
 3   Price             93 non-null     int64
 4   MPG.city          93 non-null     int64
 5   AirBags           93 non-null     object
 6   Horsepower        93 non-null     int64
 7   Passengers        93 non-null     int64
 8   Rear.seat.room    93 non-null     float64
 9   Luggage.room      93 non-null     float64
 10  price_normalized  93 non-null     float64
 11  Horsepower_std    93 non-null     float64
dtypes: float64(4), int64(4), object(4)
memory usage: 8.8+ KB

In [ ]:
len(df['Manufacturer'].unique())

32

In [ ]:
len(df['Model'].unique())

93

In [ ]:
len(df['Type'].unique())

6

In [ ]:
len(df['AirBags'].unique())

2

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [ ]:
df_encoded = label_encoder.fit_transform(df["Type"])

In [ ]:
df_encoded

array([3, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 4, 2, 5, 5, 1, 4, 1, 0, 1,
       3, 3, 0, 5, 2, 4, 3, 1, 3, 3, 0, 4, 4, 5, 2, 1, 3, 4, 4, 3, 0, 3,
       3, 4, 2, 2, 2, 2, 2, 1, 3, 3, 0, 5, 4, 0, 2, 4, 2, 3, 2, 3, 0, 5,
       2, 0, 2, 5, 1, 4, 3, 0, 4, 2, 1, 0, 3, 3, 3, 0, 3, 3, 4, 2, 5, 3,
       5, 0, 4, 0, 2])

In [ ]:
df['type_encoded'] = df_encoded

In [ ]:
df.head(3)

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room,price_normalized,Horsepower_std,type_encoded
0,Acura,Integra,Small,3259500,25,Driver only,140,5,26.5,11.0,0.155963,-0.073484,3
1,Acura,Legend,Midsize,6949500,18,Driver & Passenger,200,5,30.0,15.0,0.486239,1.078322,2
2,Audi,90,Compact,5965500,20,Driver only,172,5,28.0,14.0,0.398165,0.540813,0